### ISSUE TITLE
Give all players the same seed on "New clue"

### ISSUE THREAD

**Issue by tuukka** [gjeuken/telewave#10]
When playing on multiple browsers (remotely starting with the same seed), it would be convenient if "New clue" gave the same (pseudo random, not true random) new seed on each browser.

I see it used to be like that before commit 0c4c50f "new seed true random". If the new functionality is sometimes preferable, could it be another button such as "New seed"?

As an option, how about appending a predictable "clue number" to the seed? If the initial seed was "1234", then "New clue" would step through seeds "1234-2", "1234-3" etc. This way, a four-digit seed would provide 10000 different "games" as opposed to just 10000 different clues.

**Comment by gjeuken** [comment]
Thanks for the suggestion.
This is something that was requested before in #8. At the moment I thought that implementation was too disruptive to the normal workflow of most users.
However, I like your solution much better, and I've implemented it in b6977de.
Let me know if you have any issues with it.

**Comment by tuukka** [comment]
Awesome - thank you!
