### ISSUE TITLE
Slider is continous/non-stepped

### ISSUE THREAD

**Issue by Electro707** [gjeuken/telewave#3]
The slider is a continuous one instead of it having a step of 1/100. This makes it so that in a remote group setting, where a team agrees on a certain percentage, the points can vary depending on how the "leader" of that group or whoever makes the guess adjusted the slider.
Here is an example of what I mean, where here the group agrees on 23% as their answer:
![image](https://user-images.githubusercontent.com/15680882/82002235-498da080-962b-11ea-8214-aa0f4d56a873.png)
![image](https://user-images.githubusercontent.com/15680882/82002280-675b0580-962b-11ea-9376-92a44632a619.png)
This probably can be fixed by setting the slider with a step of 1/100, then having the red/yellow/green area be in between whole numbers. I can do that if you would like/if you're busy (I'm not sure if that's supposed to be part of the game mechanic or not)

**Comment by gjeuken** [comment]
Hi,
Thanks a lot contributing to this.
The slider itself outputs a number from 0 to 1000, and the target is also generated in the same range. I wanted to do this to emulate as well as possible the feeling of the physical game, and only 100 steps seemed not enough for the purpose
The numbers in the bottom (0 to 100) were a later addition, intended to make it easier for teams to discuss via video call, and was never meant to be an integral part of the answer (thus they are optional). In fact, the official rulebook for the game advises against using percentages to when discussing the position of the dial.
One possible solution would be to display the numbers in 1/1000 increments, but that looks to me as unnecessary precision for this type of game.
Thoughts?

**Comment by Electro707** [comment]
I think instead the slider should be in 100's increment. While I agree it removes the physical game's feeling, I think it makes it better if it's played remotely. As an example, when I played this game with my co-workers, the number was used to reach an agreement as a team as to where to put the slider, instead of something vague like "A bit to the left", especially if the team "leader" isn't sharing their screen. Either that or like you said the number should be between 0 and 1000, but like you said that's unnecessary precision and a bit much for the game.
Another possibility is to have a checkbox determining the slider's range(either 0-1000 for a more physical feel or 0-100 when coordinating the selection remotely), but I am not sure if that will add unnecessary to the game. Let me know what you think!

**Comment by gjeuken** [comment]
Hi,
I just tested both solutions but was not very happy with either one.
I've heard from a few people that prefer to play it without the numbers, so I wouldn't want to change the slider to larger increments, and I also feel like adding another decimal precision on the numbers would go against the casual feel of the game.
However, if you'd like to fork the code to make either of these changes, I'd be happy to point you to the changes that need to be made.
Thanks again for the comments, I much appreciate contributions to this project :)
