### ISSUE TITLE
match "quality name" box width to slide width

### ISSUE THREAD

**Issue by jmarq** [gjeuken/telewave#4]
Hello! Game is a blast, had fun playing it with friends tonight.

A nitpick suggestion: what if the colored boxes that have the names of the two ends of the spectrum combined to have a width that equaled the slider interface?  Like this:
![telewave](https://user-images.githubusercontent.com/3515420/82628828-84f01800-9bb3-11ea-949b-e94ec335a309.png)

![telewave2](https://user-images.githubusercontent.com/3515420/82629134-70f8e600-9bb4-11ea-97a8-3c4675b830e9.png)

there is something more intuitive about it to me to have a more direct mapping between the widths. 
(a color gradient could be cool too)
I'd be happy to put in a PR for this change (tiny css width change on the table element) if it's something you agree with. regardless, thanks for making this! well done.

**Comment by gjeuken** [comment]
Hi,
Thanks so much for the suggestion, I really appreciate contributions to this small project.
With the table I wanted to recreate the feel of the game cards, but so far I had not introduced the arrows at the top, and I see now how this can be confusing for first time players.
After testing your solution and implementing the arrows, I felt like the arrows on top are more intuitive and also mimic the game more, so I went ahead and pushed this change.
Let me know if this addresses your concerns.
Thanks again :)
